# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aeed93d69bf9123b9ca60fde9cd81e42dfe1b669bacbbac2b42f032c0f8f912460542e78ee413c42e0f87067d18aaf4135b51017b3c7c7a919bab77d682720d

test:
  secret_key_base: d88b326356de93f808633d4086ebda634cd154515ca88156a536d0dac0ac2e74f19bbe688107e56a68b0258c151358ca9616e9be92de1655b997d04c2f875aeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
